name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches: ["master"]

env:
  PROJECT_ID: 'peaceful-harbor-476816-p4'
  REGION: 'europe-west2'
  SERVICE: 'fraud-detection-model'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/390826133051/locations/global/workloadIdentityPools/github'
  # Set this to the service account you created (replace with your actual SA)
  SERVICE_ACCOUNT: 'gha-deployer@peaceful-harbor-476816-p4.iam.gserviceaccount.com'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: 'Docker Auth'
        uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Set image name'
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: 'Build and push container image'
        run: |-
          docker build --tag "${IMAGE}" .
          docker push "${IMAGE}"

      - id: deploy
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          project_id: '${{ env.PROJECT_ID }}'
          image: '${{ env.IMAGE }}'
          allow_unauthenticated: true

      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
